### ISSUE TITLE
CodeHarbor <-> CodeOcean

### ISSUE THREAD

**Issue by leoselig** [openHPI/codeharbor#16]
**CodeHarbor:**
- [x] #1 CRUD Account Links per User
- [x] #8 Add OAuth2 tokens to account links
- [x] #5 Serialize meta data (title, description) as ProFormA XML
- [x] #2 Add "Send to..." dropdown on exercises #2
- [x] #4 Push to external account from exercises
- [x] #17 Serialize normal files as ProFormA-XML
- [x] #35 Serialize property "main file" on files vial ProFormA-XML
- [x] #36 Serialize tests (test files) as ProFormA-XML (requires data model change)
- [x] #37 Serialize programming language and version (no counter-part in CodeOcean because execution environments might not exist)
- [x] Serialize model solutions as ProFormA-XML (no counter-part in CodeOcean because it does not know the concept of model solutions)

**CodeOcean:**
- [x] leoselig/codeocean#2 CodeHarbour: CRUD CodeHabor Links per user
- [x] leoselig/codeocean#1 CodeHarbour: Import exercise (meta data only) as ProFormA-XML via POST endpoint
- [x] leoselig/codeocean#3 CodeHarbor: Import exercise files from ProFormA-XML
- [x] leoselig/codeocean#4 Deserialize tests (test files) from ProFormA-XML
- [ ] leoselig/codeocean#5 Deserialize programming language and version
- [ ] Deserialize model solutions (called "reference implementation" in CodeOcean) from ProFormA-XML

**Comment by kkoehn** [comment]
fixed in #191
